### PR TITLE
modified front page

### PR DESCRIPTION
**Pull request by lucascreery**

### CODE REVIEW

**Comment by phcreery** [comment]
Are you importing the images from the client directory?
```
import slide1 from './slide1.jpg'
import slide2 from './slide2.png'
```

also is `import {Parallax, ParallaxLayer} from 'react-spring/renderprops-addons'` a new npm module?

**Comment by lucascreery** [comment]
I forgot about those lines. You should get rid of them. I was using them
for testing, but they aren't necessary. The photos are imported from the
server side.

**Comment by phcreery** [comment]
Like what we have seen before, you should move line 44-51 into `if (res.status == 200)` or else you could see that error: `cannot map undefined` when there are no photos in that folder.

` newState.photos = await res.data.files.map((image) => ({`

**Comment by phcreery** [comment]
> I forgot about those lines. You should get rid of them. I was using them for testing, but they aren't necessary. The photos are imported from the server side.

Okay, if you commit that (to branch `front-page`), it will update in this PR

**Comment by lucascreery** [comment]
Okay I did that.

**Pull request closed without merging**
